name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # main にプッシュしたら発火

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # ← サブモジュール取得を完全にする

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Debug Themes Directory
        run: |
          echo "Checking themes directory..."
          ls -la themes/ || exit 1

      - name: Debug Shortcodes
        run: |
          echo "Checking shortcodes directory..."
          ls -la layouts/shortcodes/ || exit 1

      - name: Debug Theme Shortcodes
        run: |
          echo "Checking theme shortcodes..."
          ls -la themes/congo/layouts/shortcodes/ || exit 1

      - name: Clean Hugo Modules Cache
        run: hugo mod clean

      - name: Build site
        run: hugo -v --themesDir themes -d public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
