name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # main に push されたら発火

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
        with:
          submodules: true  # サブモジュールも取得

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: スクリプト実行
        run: bash deploy.sh  # ここで `deploy.sh` を実行
