name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # mainにプッシュしたら発火

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true  # ← ここでサブモジュールを取得する

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Get Hugo Modules
        run: hugo mod get -u
        
      - name: Build site
        run: hugo -d public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


