name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # main にプッシュしたら発火

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules:  recursive

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Reset Hugo Modules
        run: rm -rf ~/go/pkg/mod && hugo mod tidy

      - name: Debug Build Environment
        run: |
          pwd
          ls -la
          ls -la themes/
      - name: Debug Shortcode Files
        run: |
           echo "Checking shortcodes directory..."
           ls -la layouts/shortcodes/
  
      - name: Build site
        run: hugo -v --themesDir themes -d public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
